1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of functions and methods that allows you to perform specific tasks without having to write the code yourself. We use Python libraries to save time, leverage existing solutions, and enhance the functionality of our programs by easily incorporating pre-written code for various tasks or functionalities.

2. What is the difference between Numpy array an List?

A NumPy array is a multidimensional grid of values, optimized for numerical operations, offering efficient storage and operations on large datasets. Lists, on the other hand, are basic data structures in Python that can hold elements of different data types, but lack the specialized numerical computation capabilities and efficiency of NumPy arrays.

3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [13]:
import numpy as np

lis = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
arr = np.array(lis)
print(arr.ndim)
print(arr.size)
print(arr.shape)

2
12
(3, 4)


4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [14]:
arr[0]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [15]:
arr[2 , [3]]

array([12])

6. Write code to extract all odd -indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [20]:
arr[:, [0,2]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

7. How can you generate a ran^om 3x3 matrix with values between 0 and 1?

In [23]:
arr1 = np.random.rand(3, 3)
arr1

array([[0.39069147, 0.75898937, 0.53303821],
       [0.81995385, 0.63127508, 0.01057809],
       [0.27044799, 0.37484575, 0.45198926]])

8. Describe the difference between np.random.rand and np.random.randn?

9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [26]:
arr_new = np.expand_dims(arr, axis=1)  # Increase dimensions
print(arr_new)

[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]


10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [27]:
arr_transposed = np.transpose(arr)
print(arr_transposed)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [40]:
lis1 =  [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
lis2 =  [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

mat1 = np.array(lis1)
mat2 = np.array(lis2)

In [37]:
mat1 + mat2  # addtion between both matrix

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [43]:
mat1 * mat2 # index multiplication

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [45]:
mat2 - mat1  #


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [46]:
mat2 / mat1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

12.  Which function in Numpy can be used to swap the byte or^er of an array?

In [44]:
arr = np.array([1, 2, 3, 4], dtype=np.int32)

arr.byteswap(True)

print("Array with byte order swapped:", arr)


Array with byte order swapped: [16777216 33554432 50331648 67108864]


13.  What is the significance of the np.linalg.inv function?

14. What does the np.reshape function do, and how is it use^?

15. What is broa^casting in Numpy?